config/routes.rb
Rails.application.routes.draw do
  resources :recoms

  resources :recomendacions

  resources :caterecos

  devise_for :usuarios
  root :to => 'inicio#index'
  get 'inicio/index'

end

app/models/catereco.rb
class Catereco < ActiveRecord::Base
  has_many :recom
  has_many :recomendacion, :through => :recom
  validates :tipo, presence: { message: "Campo Obligatorio"}
  
end

app/models/recom.rb
class Recom < ActiveRecord::Base
  belongs_to :recomendacion
  belongs_to :catereco
end

app/models/recomendacion.rb
class Recomendacion < ActiveRecord::Base
  belongs_to :usuario
  has_many :recom
  has_many :catereco, :through => :recom
  validates :taller, presence: { message: "Campo Obligatorio"}
  validates :taller, length:{
    minimum: 4,
    too_short: "Minimo %{count}caracteres"
  }
  validates :direccion, presence: { message: "Campo Obligatorio"}
  validates :direccion, length:{
    minimum: 4,
    too_short: "Minimo %{count}caracteres"
  }
  validates :comuna, presence: { message: "Campo Obligatorio"}
  validates :comuna, length:{
    minimum: 4,
    too_short: "Minimo %{count}caracteres"
  }
  validates :ciudad, presence: { message: "Campo Obligatorio"}
  validates :ciudad, length:{
    minimum: 4,
    too_short: "Minimo %{count}caracteres"
  }
  validates :comentario, presence: { message: "Campo Obligatorio"}
  validates :comentario, length:{
    minimum: 5,
    too_short: "Minimo %{count}caracteres"
  }
  validates :calificacion, presence: { message: "Campo Obligatorio"}
  validates :calificacion, length:{
    minimum: 4,
    too_short: "Minimo %{count}caracteres"
  }


  end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/caterecos_controller.rb
class CaterecosController < ApplicationController
  before_action :set_catereco, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @caterecos = Catereco.all
    respond_with(@caterecos)
  end

  def show
    respond_with(@catereco)
  end

  def new
    @catereco = Catereco.new
    respond_with(@catereco)
  end

  def edit
  end

  def create
    @catereco = Catereco.new(catereco_params)
    @catereco.save
    respond_with(@catereco)
  end

  def update
    @catereco.update(catereco_params)
    respond_with(@catereco)
  end

  def destroy
    @catereco.destroy
    respond_with(@catereco)
  end

  private
    def set_catereco
      @catereco = Catereco.find(params[:id])
    end

    def catereco_params
      params.require(:catereco).permit(:tipo)
    end
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  end
end

app/controllers/recomendacions_controller.rb
class RecomendacionsController < ApplicationController
  before_action :set_recomendacion, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @recomendacions = Recomendacion.all
    respond_with(@recomendacions)
  end

  def show
    respond_with(@recomendacion)
  end

  def new
    @recomendacion = Recomendacion.new
    respond_with(@recomendacion)
  end

  def edit
  end

  def create
    @recomendacion = Recomendacion.new(recomendacion_params)
    @recomendacion.save
    respond_with(@recomendacion)
  end

  def update
    @recomendacion.update(recomendacion_params)
    respond_with(@recomendacion)
  end

  def destroy
    @recomendacion.destroy
    respond_with(@recomendacion)
  end

  private
    def set_recomendacion
      @recomendacion = Recomendacion.find(params[:id])
    end

    def recomendacion_params
      params.require(:recomendacion).permit(:tipo, :taller, :direccion, :comuna, :ciudad, :comentario, :calificacion, :usuario_id)
    end
end

app/controllers/recoms_controller.rb
class RecomsController < ApplicationController
  before_action :set_recom, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @recoms = Recom.all
    respond_with(@recoms)
  end

  def show
    respond_with(@recom)
  end

  def new
    @recom = Recom.new
    respond_with(@recom)
  end

  def edit
  end

  def create
    @recom = Recom.new(recom_params)
    @recom.save
    respond_with(@recom)
  end

  def update
    @recom.update(recom_params)
    respond_with(@recom)
  end

  def destroy
    @recom.destroy
    respond_with(@recom)
  end

  private
    def set_recom
      @recom = Recom.find(params[:id])
    end

    def recom_params
      params.require(:recom).permit(:recomendacion_id, :catereco_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caterecos_helper.rb
module CaterecosHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/recomendacions_helper.rb
module RecomendacionsHelper
end

app/helpers/recoms_helper.rb
module RecomsHelper
end

app/views/caterecos/_form.html.erb
<%= form_for(@catereco) do |f| %>
  <% if @catereco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@catereco.errors.count, "error") %> prohibited this catereco from being saved:</h2>

      <ul>
      <% @catereco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/caterecos/edit.html.erb
<h1>Editing catereco</h1>

<%= render 'form' %>

<%= link_to 'Show', @catereco %> |
<%= link_to 'Back', caterecos_path %>

app/views/caterecos/index.html.erb
<h1>Categorias</h1>
<p>Indicanos a que categoria pertenece tu recomendacion</p>
<table class="table">
  <thead>
    <tr>
      <th>Tipo de Servicio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @caterecos.each do |catereco| %>
      <tr>
        <td><%= catereco.tipo %></td>
        <td><%= link_to 'Show', catereco %></td>
        <td><%= link_to 'Edit', edit_catereco_path(catereco) %></td>
        <td><%= link_to 'Destroy', catereco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Categoria', new_catereco_path %>
<BODY BACKGROUND="<%= asset_path 'rodamientos.jpg' %>">

app/views/caterecos/new.html.erb
<h1>New catereco</h1>

<%= render 'form' %>

<%= link_to 'Back', caterecos_path %>

app/views/caterecos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @catereco.tipo %>
</p>

<%= link_to 'Edit', edit_catereco_path(@catereco) %> |
<%= link_to 'Back', caterecos_path %>

app/views/inicio/index.html.erb
<h1>Bienvenidos a Mundo Tuerca</h1>
<p>Mundo Tuerca es un espacio donde podrás dejar tus experiencias, datos o malos ratos referente</p>
<p>a tu entorno automovilistico.</p>
<p>Tienes un buen dato que compartir?</p>
<p>Te cobraron mucho para un mal servicio?</p>
<p>Quieres compartir tu pasion con nosotros?</p>
<p>Este es tu espacio</p>
<BODY BACKGROUND="<%= asset_path 'rodamientos.jpg' %>">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MundoTuerca</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>
<%= render 'shared/navbar'%>
<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>
<div class="panel panel-default">
<table class="table table-hover" >
</div>

<div class="container">
<%= yield %>
</div>
<div class="panel panel-default">
<table class="table table-hover" >
</div>

</body>
</html>

app/views/recomendacions/_form.html.erb
<%= form_for(@recomendacion) do |f| %>
  <% if @recomendacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recomendacion.errors.count, "error") %> prohibited this recomendacion from being saved:</h2>

      <ul>
      <% @recomendacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :taller %><br>
    <%= f.text_field :taller %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :comuna %><br>
    <%= f.text_field :comuna %>
  </div>
  <div class="field">
    <%= f.label :ciudad %><br>
    <%= f.text_field :ciudad %>
  </div>
  <div class="field">
    <%= f.label :comentario %><br>
    <%= f.text_area :comentario %>
  </div>
  <div class="field">
    <%= f.label :calificacion %><br>
    <%= f.text_field :calificacion %>
  </div>
  <div class="field">
    <%= f.hidden_field :usuario_id, :value => current_usuario.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recomendacions/edit.html.erb
<h1>Editing recomendacion</h1>

<%= render 'form' %>

<%= link_to 'Show', @recomendacion %> |
<%= link_to 'Back', recomendacions_path %>

app/views/recomendacions/index.html.erb
<h1>Recomendaciones</h1>
<p>Sea buena o mala tu experiencia con algun taller o conocido</p>
<p>Cuentanos donde fue y quien te atendio</p>
<table class="table">
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Taller</th>
      <th>Direccion</th>
      <th>Comuna</th>
      <th>Ciudad</th>
      <th>Comentario</th>
      <th>Calificacion</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recomendacions.each do |recomendacion| %>
      <tr>
        <% if current_usuario.email == recomendacion.usuario.email %>
        <td><%= recomendacion.tipo %></td>
        <td><%= recomendacion.taller %></td>
        <td><%= recomendacion.direccion %></td>
        <td><%= recomendacion.comuna %></td>
        <td><%= recomendacion.ciudad %></td>
        <td><%= recomendacion.comentario %></td>
        <td><%= recomendacion.calificacion %></td>
        <td><%= recomendacion.usuario.email %></td>
        <td><%= link_to 'Show', recomendacion %></td>
        <td><%= link_to 'Edit', edit_recomendacion_path(recomendacion) %></td>
        <td><%= link_to 'Destroy', recomendacion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Recomendacion', new_recomendacion_path %>
<BODY BACKGROUND="<%= asset_path 'rodamientos.jpg' %>">

app/views/recomendacions/new.html.erb
<h1>New recomendacion</h1>

<%= render 'form' %>

<%= link_to 'Back', recomendacions_path %>

app/views/recomendacions/show.html.erb
<p id="notice"><%= notice %></p>

  <% if current_usuario.email == @recomendacion.usuario.email %>
<p>
  <strong>Tipo:</strong>
  <%= @recomendacion.tipo %>
</p>

<p>
  <strong>Taller:</strong>
  <%= @recomendacion.taller %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @recomendacion.direccion %>
</p>

<p>
  <strong>Comuna:</strong>
  <%= @recomendacion.comuna %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @recomendacion.ciudad %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @recomendacion.comentario %>
</p>

<p>
  <strong>Calificacion:</strong>
  <%= @recomendacion.calificacion %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @recomendacion.usuario.email %>
</p>

<%= link_to 'Edit', edit_recomendacion_path(@recomendacion) %>
<% end %>
<%= link_to 'Back', recomendacions_path %>

app/views/recoms/_form.html.erb
<%= form_for(@recom) do |f| %>
  <% if @recom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recom.errors.count, "error") %> prohibited this recom from being saved:</h2>

      <ul>
      <% @recom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
        <%= f.label :recomendacion_id %><br>
         <%= f.select( "recomendacion_id",Recomendacion.all.collect{|l| [ l.tipo, l.id ] }, {include_blank: 'Seleccione Recomendacion'}) %>
      </div>
      <div class="field">
        <%= f.label :catereco_id %><br>
         <%= f.select( "catereco_id",Catereco.all.collect{|l| [ l.tipo, l.id ] }, {include_blank: 'Seleccione Categoria'}) %>
      </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recoms/edit.html.erb
<h1>Editing recom</h1>

<%= render 'form' %>

<%= link_to 'Show', @recom %> |
<%= link_to 'Back', recoms_path %>

app/views/recoms/index.html.erb
<h1>Categoria de Recomendaciones</h1>

<table class="table">
  <thead>
    <tr>
      <th>Recomendaciones</th>
      <th>Categorias</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recoms.each do |recom| %>
      <tr>
        <td><%= recom.recomendacion.tipo %></td>
        <td><%= recom.catereco.tipo %></td>
        <td><%= link_to 'Show', recom %></td>
        <td><%= link_to 'Edit', edit_recom_path(recom) %></td>
        <td><%= link_to 'Destroy', recom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Categoria de Recomendacion', new_recom_path %>
<BODY BACKGROUND="<%= asset_path 'rodamientos.jpg' %>">

app/views/recoms/new.html.erb
<h1>New recom</h1>

<%= render 'form' %>

<%= link_to 'Back', recoms_path %>

app/views/recoms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recomendacion:</strong>
  <%= @recom.recomendacion.tipo %>
</p>

<p>
  <strong>Catereco:</strong>
  <%= @recom.catereco.tipo %>
</p>

<%= link_to 'Edit', edit_recom_path(@recom) %> |
<%= link_to 'Back', recoms_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
<a class="navbar-brand" href="<%=root_path%>">Home</a>
    </div>
<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <% if usuario_signed_in? %>
       <li><a href="<%= recomendacions_path %>">Recomendaciones</a></li>
       <li><a href="<%= caterecos_path %>">Categoria</a></li>
       <li><a href="<%= recoms_path %>">Categoria Recomendaciones</a></li>
        <% end %>
          </ul>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">

            <% if usuario_signed_in? %>

            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if usuario_signed_in? %>
            <li><a> <%= current_usuario.email %> </a></li>
              <li><a href="<%= edit_usuario_registration_path(current_usuario) %>">Editar Perfil</a></li>
              <li><a href="<%= destroy_usuario_session_path %>", data-method="delete">Cerrar Session</a></li>
            <% else %>
              <li><a href="<%= new_usuario_session_path %>">Ingresar</a></li>
              <li><a href="<%= new_usuario_registration_path %>">Registrarse</a></li>
            <% end %>
          </ul>
        </div></li><!-- /.navbar-collapse -->
</nav>
<style>
th{
padding: 20px;
}
</style>
<style>
body {background-color:lightgray}
h1   {color:blue}
p    {color:green}
</style>
</nav>